name: Deploy Server

on:
  push:
    branches: [ main,test_branch ]
    paths:
      - 'server/**'
      - 'Dockerfile.server'
      - 'requirements.txt'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Latest Model
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: train.yml
        branch: main
        name: trained-face-model
        if_no_artifact_found: warn
        
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/face-api:latest

    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/face-api:latest
          docker stop face-api || true
          docker rm face-api || true
          docker run -d --name face-api -p 3000:3000 --network host ${{ secrets.DOCKERHUB_USERNAME }}/face-api:latest