name: Retrain Face Model

on:
  push:
    branches: [ main ]
    paths:
      - 'model_testing/**'
      - 'dataset.dvc'
  workflow_dispatch: # Allows you to manually click "Run" in GitHub

jobs:
  train-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "dvc[azure]"

    - name: Pull Dataset from Azure via DVC
      run: |
        dvc remote modify --local myremote account_name "harsh23"
        dvc remote modify --local myremote account_key "${{ secrets.AZURE_STORAGE_KEY }}"
        dvc pull
  
    - name: Extract Facial Embeddings
      run: python model_testing/extract_embeddings.py

    - name: Run Evaluation
      run: python model_testing/eval.py

    - name: Train Production Model
      run: python model_testing/train_model.py

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-face-model
        path: face_model.pkl